// IMPORTANT: Don't change these constants. 
// This file is generated by a script.
// If you want to change these values, just change it where it's used.

// Professional business constants
export const BREEZY_PROFESSIONAL_TOKEN = "3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39";

// Business information
export const PROFESSIONAL_NAME = "Weinman Law Offices";
export const PROFESSIONAL_PHONE = "+17184422010";
export const PROFESSIONAL_PHONE_ALT = "+17189578121";
export const PROFESSIONAL_FAX = "866-934-6626";
export const PROFESSIONAL_EMAIL = "Weinman@StatenIslandLaw.com";
export const PROFESSIONAL_ADDRESS = "260 Christopher Lane, Staten Island, NY 10314";

// Social Media Links
export const SOCIAL_MEDIA = {
  facebook: "https://www.facebook.com/StatenIslandLaw",
  linkedin: "https://www.linkedin.com/in/statenislandlaw",
  instagram: "https://www.instagram.com/statenislandlaw",
  twitter: "https://twitter.com/StatenIslandLaw",
  tiktok: "https://www.tiktok.com/@statenislandlaw",
  youtube: "https://www.youtube.com/@statenislandlaw",
};

// Professional images
export const PROFESSIONAL_IMAGES = [
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/0552d3074780f0802def15f029c6e855438464d908a52b154903abe398c8.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/68bccc81c314fd5d12220a970c9dbbadf8ebbedd5b8d0d698eb1bfd4249d.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/c9f23cad2788c680c645509c04af62f0e6e4ac9d21fff8b19c41b226b83e.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/5e3405f5455f447e24c6ed2f7d29e0a0fa9231a32493fd48ba4e0ba0b691.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/c7680bb554fc0adc85b9ea3959df4054d177a45aff74da764ebaaab72d9e.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/d10d47d2ad040d8fb9e405bda7091b0ba4ef48658c6d96929896b93b6ebf.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/012017b78b50b5cef9b66168b5b55c084f5cfd2067ee371ac7a7f6eb609c.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/7e805a817e812e857025e59ab6341e75390f3e99517e783b14b0f37bccac.jpg",
  "https://breezy-sites.s3.amazonaws.com/site_images/3538dc64da8e6f3cab2a245299e0e3dd6655ba6606b507776332400b7f39/5a293302e713c811ba293b65845355283605fdf61459b3cb5cc274a43eb5.jpg",
];

// Page publication dates
export const PAGE_DATES = {
  homepage: {
    published: "2024-01-15",
    lastUpdated: "2024-04-21"
  },
  about: {
    published: "2024-01-15",
    lastUpdated: "2024-04-21"
  },
  services: {
    published: "2024-01-15",
    lastUpdated: "2024-04-21"
  }
};
